# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: My New Html

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Node.js environment
      - uses: actions/setup-node@v1
        with:
          version: 12
      - name: GitHub Action for Yarn
      - uses: Borales/actions-yarn@v2.3.0
        with:
          # Yarn Install
          cmd: install # npm install / yarn install

      - name: Creating build
        run: yarn build

      - name: Installing Surge
        run: npm install -g surge
      - name: Deploying on surge
        run: surge ./build  wibal-html.surge.sh --token ${{secrets.SURGE_TOKEN}}
